# Default values for edgedelta.

image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""
apiKey: ""

resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi
