kind: Service
apiVersion: v1
metadata:
  name: {{ include "edgedelta.fullname" . }}-coordinator-svc
  namespace: {{ .Release.Namespace }}
  labels:
    version: v1
    kubernetes.io/cluster-service: "true"
    edgedelta/service-type: "coordinator"
spec:
  selector:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    edgedelta/agent-type: processor
  ports:
    - port: {{ .Values.coordinatorProps.port }}
      name: coordinator-port