{{- if .Values.agentUpdater.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: agent-updater-roles
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-updater-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: User
  name: "system:serviceaccount:{{ .Release.Namespace }}:default"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: agent-updater-roles
  apiGroup: rbac.authorization.k8s.io
---
{{- if .Capabilities.APIVersions.Has "batch/v1beta1" }}
apiVersion: batch/v1beta1
{{- else }}
apiVersion: batch/v1
{{- end }}
kind: CronJob
metadata:
  name: edgedelta-updater
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "*/60 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: edgedelta-updater-container
            image: {{ .Values.agentUpdater.image }}
            imagePullPolicy: Always
            command:
            - /ko-app/agent-updater
            - --config
            - /var/edgedelta/updater-config.yml
            volumeMounts:
              - name: config-volume
                mountPath: /var/edgedelta
            env:
            - name: KUBE_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBE_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          restartPolicy: Never
          volumes:
          - name: config-volume
            configMap:
              name: {{ .Release.Name }}
{{- end }}