{{- if .Values.aggregatorProps.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edgedelta.fullname" . }}-aggregator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    edgedelta/agent-type: aggregator
spec:
  replicas: 1
  strategy:
    type: Recreate # Rolling update gets stuck with ReadWriteOnce PVC
  selector:
    matchLabels:
      {{- include "edgedelta.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.annotations }}
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
      {{- end }}
      labels:
      {{- include "edgedelta.labels" . | nindent 8 }}
      {{- if .Values.labels }}
        {{- toYaml .Values.labels | nindent 8 }}
      {{- end }}
      {{- if .Values.secretApiKey.key }}
      {{ $lookupResult := lookup "v1" "Secret" .Release.Namespace (include "apiKeySecretName" .) }}
      {{- if .Values.secretApiKey.value }}
        edgedelta/api-key-sha: {{ .Values.secretApiKey.value | sha256sum | substr 0 48 }}
      {{- else if $lookupResult }}
        edgedelta/api-key-sha: {{ index $lookupResult.data .Values.secretApiKey.key | b64dec | sha256sum | substr 0 48 }}
      {{- end }}
      {{- end }}
        edgedelta/agent-type: aggregator
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "edgedelta.fullname" . }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-aggregator
        image: {{ .Values.image.fullPath | default (printf "%s/%s:%s" .Values.repository .Values.image.name (.Values.image.tag | default .Chart.AppVersion)) }}
        {{- if .Values.edConfigContent }}
        command:
          - /edgedelta/edgedelta
        args:
          - -c
          - /var/edgedelta/config.yml
        {{- end }}
        ports:
          - containerPort: {{ .Values.aggregatorProps.port }}
          {{- if .Values.promPort }}
          - name: prom
            containerPort: {{ .Values.promPort }}
          {{- end }}
        env:
          {{ $enabledDataTypes := list }}
          {{- range $key, $value := .Values.aggregatorProps.enabledDataTypes }}
          {{- if $value }}
            {{ $enabledDataTypes = append $enabledDataTypes $key }}
          {{- end }}
          {{- end }}
          - name: ED_AGENT_MODE
            value: aggregator
          - name: ED_AGGREGATOR_LISTEN_PORT
            value: "{{ .Values.aggregatorProps.port }}"
          - name: ED_AGGREGATOR_ENABLED_DATA_TYPES
            value: {{ join "," (sortAlpha $enabledDataTypes) }}
          {{- if .Values.aggregatorProps.usePersistentVolume }}
          - name: ED_AGGREGATOR_SRC_MAP_PATH
            value: "/edgedelta/data/src_mapping.json"
          {{- end }}
            - name: ED_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: ED_K8S_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: ED_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          {{- if .Values.apiKey }}
          - name: ED_API_KEY
            value: {{ .Values.apiKey | quote }}
          {{- else if .Values.secretApiKey.key }}
          {{ $lookupResult := lookup "v1" "Secret" .Release.Namespace (include "apiKeySecretName" .) }}
          {{- if or $lookupResult .Values.secretApiKey.value .Values.secretApiKey.enable }}
          - name: ED_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "apiKeySecretName" . }}
                key: {{ .Values.secretApiKey.key }}
          {{- end }}
          {{- end }}
          {{- if .Values.storePort }}
          - name: STORE_PORT
            value: "{{ .Values.storePort }}"
          {{- end }}
          {{- if .Values.promPort }}
          - name: ED_PROM_PORT
            value: "{{ .Values.promPort }}"
          {{- end }}
          {{- if .Values.edAggregatorTraceFiles }}
          - name: ED_TRACE_FILES
            value: {{ .Values.edAggregatorTraceFiles | quote }}
          {{- end }}
          {{- if .Values.edApiEndpoint }}
          - name: ED_API_ENDPOINT
            value: {{ .Values.edApiEndpoint }}
          {{- end }}
          {{- if .Values.edBackendDisabled }}
          - name: ED_BACKEND_DISABLED
            value: "{{ .Values.edBackendDisabled }}"
          {{- end }}
          {{- if .Values.edSkipConfDownload }}
          - name: ED_SKIP_CONF_DOWNLOAD
            value: "{{ .Values.edSkipConfDownload }}"
          {{- end }}
          {{- if .Values.edTagOverride }}
          - name: ED_TAG_OVERRIDE
            value: {{ .Values.edTagOverride }}
          {{- end }}
          {{- if .Values.edClusterName }}
          - name: ED_CLUSTER_NAME
            value: {{ .Values.edClusterName }}
          {{- end }}
          {{- if .Values.edOrgID }}
          - name: ED_ORG_ID
            value: {{ .Values.edOrgID }}
          {{- end }}
          {{- if .Values.edSuppressionMode }}
          - name: ED_SUPPRESSION_MODE
            value: "{{ .Values.edSuppressionMode }}"
          {{- end }}
          {{- if .Values.edWorkflows }}
          - name: ED_WORKFLOWS
            value: {{ .Values.edWorkflows }}
          {{- end }}
          {{- if .Values.edWorkflowPrefixes }}
          - name: ED_WORKFLOW_PREFIXES
            value: {{ .Values.edWorkflowPrefixes }}
          {{- end }}
          {{- if .Values.httpProxy }}
          - name: HTTP_PROXY
            value: {{ .Values.httpProxy }}
          {{- end }}
          {{- if .Values.httpsProxy }}
          - name: HTTPS_PROXY
            value: {{ .Values.httpsProxy }}
          {{- end }}
          {{- if .Values.noProxy }}
          - name: NO_PROXY
            value: {{ .Values.noProxy }}
          {{- end }}
          {{- if .Values.edCustomTags }}
          - name: ED_CUSTOM_TAGS
            value: "{{ .Values.edCustomTags }}"
          {{- end }}
          {{- if .Values.aggregatorProps.goMemLimit }}
          - name: GOMEMLIMIT
            value: {{ .Values.aggregatorProps.goMemLimit }}
          {{- end }}
          {{- range .Values.envs }}
          - name: {{ .name }}
            value: "{{ .value }}"
          {{- end }}
          {{- range .Values.secrets }}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ .secretKeyRef.name }}
                key: {{ .secretKeyRef.key }}
          {{- end }}
        volumeMounts:
          {{- if .Values.aggregatorProps.usePersistentVolume }}
          - name: "aggregator-data"
            mountPath: "/edgedelta/data"
          {{- end }}
          - name: hostpath
            mountPath: {{ .Values.dockerContainerProps.hostPath }}
            readOnly: true
          {{- if .Values.edConfigContent }}
          - name: config-volume
            mountPath: /var/edgedelta
          {{- end }}
        resources:
          {{- toYaml .Values.aggregatorProps.resources | nindent 10 }}
        imagePullPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
        {{- if .Values.aggregatorProps.usePersistentVolume }}
        - name: aggregator-data
          persistentVolumeClaim:
            claimName: aggregator-data
        {{- end }}
        - name: hostpath
          hostPath:
            path: {{ .Values.dockerContainerProps.hostPath }}
        {{- if .Values.edConfigContent }}
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}
        {{- end }}
---
kind: Service
apiVersion: v1
metadata:
  name: ed-aggregator-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    edgedelta/agent-type: aggregator
  ports:
    - port: {{ .Values.aggregatorProps.port }}
      name: aggregator-port
---
{{- if .Values.aggregatorProps.usePersistentVolume }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aggregator-data
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.aggregatorProps.storageClassName }}
  storageClassName: {{ .Values.aggregatorProps.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}
{{- end }}