{{- if and (and .Values.secretApiKey.name .Values.secretApiKey.key) .Values.secretApiKey.value }}
{{ $lookupResult := lookup "v1" "Secret" .Release.Namespace .Values.secretApiKey.name }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.secretApiKey.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
{{- if $lookupResult }}
data:
  {{ .Values.secretApiKey.key | quote }}: {{ index $lookupResult.data .Values.secretApiKey.key }}
{{- else }}
stringData:
  {{ .Values.secretApiKey.key | quote }}: {{ .Values.secretApiKey.value | quote }}
{{- end }}
{{- end }}