{{- if .Values.archiverProps.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edgedelta.fullname" . }}-archiver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    edgedelta/agent-type: archiver
spec:
  replicas: 1
  strategy:
    type: Recreate # Rolling update gets stuck with ReadWriteOnce PVC
  selector:
    matchLabels:
      {{- include "edgedelta.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.annotations }}
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
      {{- end }}
      labels:
      {{- include "edgedelta.labels" . | nindent 8 }}
      {{- if .Values.labels }}
        {{- toYaml .Values.labels | nindent 8 }}
      {{- end }}
      {{- if and .Values.secretApiKey.name .Values.secretApiKey.key }}
      {{ $lookupResult := lookup "v1" "Secret" .Release.Namespace .Values.secretApiKey.name }}
      {{- if .Values.secretApiKey.value }}
        edgedelta/api-key-sha: {{ .Values.secretApiKey.value | sha256sum | substr 0 48 }}
      {{- else if $lookupResult }}
        edgedelta/api-key-sha: {{ index $lookupResult.data .Values.secretApiKey.key | b64dec | sha256sum | substr 0 48 }}
      {{- end }}
      {{- end }}
        edgedelta/agent-type: archiver
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "edgedelta.fullname" . }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-archiver
        image: {{ if .Values.image.fullPath }}{{ .Values.image.fullPath }}{{ else }}{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{ end }}
        {{- if .Values.edConfigContent }}
        command:
          - /edgedelta/edgedelta
        args:
          - -c
          - /var/edgedelta/config.yml
        {{- end }}
        ports:
          - containerPort: {{ .Values.archiverProps.port }}
          {{- if .Values.promPort }}
          - name: prom
            containerPort: {{ .Values.promPort }}
          {{- end }}
        env:
          - name: ED_AGENT_MODE
            value: archiver
          - name: ED_ARCHIVER_PORT
            value: "{{ .Values.archiverProps.port }}"
          - name: ED_HOST_OVERRIDE
            value: {{ .Chart.Name }}-archiver
          - name: ED_ARCHIVER_DUMP_FOLDER
            value: "/edgedelta/data"
          {{- if .Values.apiKey }}
          - name: ED_API_KEY
            value: {{ .Values.apiKey | quote }}
          {{- else if and .Values.secretApiKey.name .Values.secretApiKey.key }}
          {{ $lookupResult := lookup "v1" "Secret" .Release.Namespace .Values.secretApiKey.name }}
          {{- if or $lookupResult .Values.secretApiKey.value }}
          - name: ED_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretApiKey.name }}
                key: {{ .Values.secretApiKey.key }}
          {{- end }}
          {{- end }}
          {{- if .Values.storePort }}
          - name: STORE_PORT
            value: "{{ .Values.storePort }}"
          {{- end }}
          {{- if .Values.promPort }}
          - name: PROM_PORT
            value: "{{ .Values.promPort }}"
          {{- end }}
          {{- if .Values.edArchiverTraceFiles }}
          - name: ED_TRACE_FILES
            value: {{ .Values.edArchiverTraceFiles | quote }}
          {{- end }}
          {{- if .Values.edApiEndpoint }}
          - name: ED_API_ENDPOINT
            value: {{ .Values.edApiEndpoint }}
          {{- end }}
          {{- if .Values.edBackendDisabled }}
          - name: ED_BACKEND_DISABLED
            value: "{{ .Values.edBackendDisabled }}"
          {{- end }}
          {{- if .Values.edSkipConfDownload }}
          - name: ED_SKIP_CONF_DOWNLOAD
            value: "{{ .Values.edSkipConfDownload }}"
          {{- end }}
          {{- if .Values.edTagOverride }}
          - name: ED_TAG_OVERRIDE
            value: {{ .Values.edTagOverride }}
          {{- end }}
          {{- if .Values.edOrgID }}
          - name: ED_ORG_ID
            value: {{ .Values.edOrgID }}
          {{- end }}
          {{- if .Values.edSuppressionMode }}
          - name: ED_SUPPRESSION_MODE
            value: "{{ .Values.edSuppressionMode }}"
          {{- end }}
          {{- if .Values.edWorkflows }}
          - name: ED_WORKFLOWS
            value: {{ .Values.edWorkflows }}
          {{- end }}
          - name: ED_LEADER_ELECTION_ENABLED
            value: "0"
          {{- if .Values.edWorkflowPrefixes }}
          - name: ED_WORKFLOW_PREFIXES
            value: {{ .Values.edWorkflowPrefixes }}
          {{- end }}
          {{- if .Values.httpProxy }}
          - name: HTTP_PROXY
            value: {{ .Values.httpProxy }}
          {{- end }}
          {{- if .Values.httpsProxy }}
          - name: HTTPS_PROXY
            value: {{ .Values.httpsProxy }}
          {{- end }}
          {{- if .Values.noProxy }}
          - name: NO_PROXY
            value: {{ .Values.noProxy }}
          {{- end }}
          {{- if .Values.edCustomTags }}
          - name: ED_CUSTOM_TAGS
            value: "{{ .Values.edCustomTags }}"
          {{- end }}
          {{- if .Values.archiverProps.goMemLimit }}
          - name: GOMEMLIMIT
            value: {{ .Values.archiverProps.goMemLimit }}
          {{- end }}
          {{- range .Values.envs }}
          - name: {{ .name }}
            value: "{{ .value }}"
          {{- end }}
          {{- range .Values.secrets }}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ .secretKeyRef.name }}
                key: {{ .secretKeyRef.key }}
          {{- end }}
        volumeMounts:
          - name: archiver-data
            mountPath: /edgedelta/data
          - name: hostpath
            mountPath: {{ .Values.dockerContainerProps.hostPath }}
            readOnly: true
          {{- if .Values.edConfigContent }}
          - name: config-volume
            mountPath: /var/edgedelta
          {{- end }}
        resources:
          {{- toYaml .Values.archiverProps.resources | nindent 10 }}
        imagePullPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
        - name: archiver-data
          persistentVolumeClaim:
            claimName: archiver-data
        - name: hostpath
          hostPath:
            path: {{ .Values.dockerContainerProps.hostPath }}
      {{- if .Values.edConfigContent }}
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}
      {{- end }}
---
kind: Service
apiVersion: v1
metadata:
  name: ed-archiver-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    edgedelta/agent-type: archiver
  ports:
    - port: {{ .Values.archiverProps.port }}
      name: archiver-port
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archiver-data
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.archiverProps.storageClassName }}
  storageClassName: {{ .Values.archiverProps.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.archiverProps.diskSize | default "10Gi" }}
{{- end }}