{{- if .Values.edConfigContent }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgedelta.labels" . | nindent 4 }}
data:
  config.yml: |-
{{ tpl .Values.edConfigContent . | indent 4 }}
{{- end }}