{{- if .Values.httpRecorderProps.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: alert@edgedelta.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: {{ .Values.httpRecorderProps.ingress.class }}
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ed-httprecorder-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.httpRecorderProps.ingress.annotations }}
    {{- toYaml .Values.httpRecorderProps.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.httpRecorderProps.ingress.host }}
    secretName: tls-secret
  rules:
    - host: {{ .Values.httpRecorderProps.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ed-httprecorder-svc
                port:
                  number: {{ .Values.httpRecorderProps.port }}
{{- end }}