{{- if not (has .Values.rbac.scope (list "cluster" "namespace")) }}
{{- fail "rbac.scope must be either cluster or namespace" }}
{{- end }}
{{- if eq .Values.rbac.scope "cluster" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "edgedelta.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgedelta.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "edgedelta.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "edgedelta.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "edgedelta.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgedelta.labels" . | nindent 4 }}
rules:
# ClusterRole rules (from values.yaml clusterRoleRules)
{{- range .Values.clusterRoleRules }}
- apiGroups: {{ .apiGroups | toJson }}
  resources: {{ .resources | toJson }}
  {{- with .resourceNames }}
  resourceNames: {{ . | toJson }}
  {{- end }}
  verbs: {{ .verbs | toJson }}
{{- end }}
{{- if .Values.additionalClusterRoleRules }}
# Additional ClusterRole rules for Custom Resource Definitions (CRDs)
{{- range .Values.additionalClusterRoleRules }}
- apiGroups: {{ .apiGroups | toJson }}
  resources: {{ .resources | toJson }}
  {{- with .resourceNames }}
  resourceNames: {{ . | toJson }}
  {{- end }}
  verbs: {{ .verbs | toJson }}
{{- end }}
{{- end }}
# This is needed since OpenShift uses different KSM package which requires authentication
{{- if eq (include "isOpenShift" .) "true"}}
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
{{- end }}
---
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "edgedelta.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgedelta.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "edgedelta.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "edgedelta.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "edgedelta.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgedelta.labels" . | nindent 4 }}
rules:
# Role rules (from values.yaml roleRules)
{{- range .Values.roleRules }}
- apiGroups: {{ .apiGroups | toJson }}
  resources: {{ .resources | toJson }}
  {{- with .resourceNames }}
  resourceNames: {{ . | toJson }}
  {{- end }}
  verbs: {{ .verbs | toJson }}
{{- end }}
{{- if .Values.additionalRoleRules }}
# Additional Role rules for Custom Resource Definitions (CRDs)
{{- range .Values.additionalRoleRules }}
- apiGroups: {{ .apiGroups | toJson }}
  resources: {{ .resources | toJson }}
  {{- with .resourceNames }}
  resourceNames: {{ . | toJson }}
  {{- end }}
  verbs: {{ .verbs | toJson }}
{{- end }}
{{- end }}
---
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "edgedelta.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- if .Values.serviceAccount.labels }}
    {{- toYaml .Values.serviceAccount.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
