{{- if .Values.secretApiKey.key }}
{{ $lookupResult := lookup "v1" "Secret" .Release.Namespace (include "apiKeySecretName" .) }}
{{- if or $lookupResult .Values.secretApiKey.value }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "apiKeySecretName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
{{- if .Values.secretApiKey.value }}
stringData:
  {{ .Values.secretApiKey.key | quote }}: {{ .Values.secretApiKey.value | quote }}
{{- else if $lookupResult }}
data:
  {{ .Values.secretApiKey.key | quote }}: {{ index $lookupResult.data .Values.secretApiKey.key }}
{{- end }}
{{- end }}
{{- end }}