{{- if .Values.compactorProps.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edgedelta.fullname" . }}-compactor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    edgedelta/agent-type: compactor
spec:
  {{- if not (or .Values.compactorProps.autoscaling.enabled .Values.compactorProps.autoscaling.external) }}
  replicas: {{ default 1 .Values.compactorProps.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "edgedelta.selectorLabels" . | nindent 6 }}
      edgedelta/agent-type: compactor
  strategy:
  {{- if .Values.compactorProps.updateStrategy }}
    {{- toYaml .Values.compactorProps.updateStrategy | nindent 4 }}
  {{- else }}
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  {{- end }}
  template:
    metadata:
      {{- if or .Values.annotations .Values.podSecurity.apparmor.enabled }}
      annotations:
      {{- if .Values.podSecurity.apparmor.enabled }}
        container.apparmor.security.beta.kubernetes.io/agent: {{ .Values.podSecurity.apparmor.profile }}
      {{- end }}
      {{- if .Values.annotations }}
        {{- toYaml .Values.annotations | nindent 8 }}
      {{- end }}
      {{- end }}
      labels:
      {{- include "edgedelta.labels" . | nindent 8 }}
      {{- if .Values.labels }}
        {{- toYaml .Values.labels | nindent 8 }}
      {{- end }}
      {{- if .Values.secretApiKey.key }}
      {{ $lookupResult := lookup "v1" "Secret" .Release.Namespace (include "apiKeySecretName" .) }}
      {{- if .Values.secretApiKey.value }}
        edgedelta/api-key-sha: {{ .Values.secretApiKey.value | sha256sum | substr 0 48 }}
      {{- else if $lookupResult }}
        edgedelta/api-key-sha: {{ index $lookupResult.data .Values.secretApiKey.key | b64dec | sha256sum | substr 0 48 }}
      {{- end }}
      {{- end }}
        edgedelta/agent-type: compactor
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "edgedelta.fullname" . }}
      {{- if .Values.compactorProps.tolerations }}
      tolerations:
        {{- toYaml .Values.compactorProps.tolerations | nindent 8 }}
      {{- else if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.compactorProps.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.compactorProps.nodeSelector | nindent 8 }}
      {{- else if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.compactorProps.priorityClassName }}
      priorityClassName: {{ .Values.compactorProps.priorityClassName }}
      {{- else if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- if .Values.compactorProps.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.compactorProps.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurity.securityContextConstraints.create -}}
      {{- if and .Values.podSecurity.seLinuxContext .Values.podSecurity.seLinuxContext.seLinuxOptions }}
      securityContext:
        seLinuxOptions:
{{ toYaml .Values.podSecurity.seLinuxContext.seLinuxOptions | indent 10 }}
      {{- end }}
      {{- else if eq (include "isOpenShift" .) "true"}}
      securityContext:
        seLinuxOptions:
          user: "system_u"
          role: "system_r"
          type: "spc_t"
          level: "s0"
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-compactor
        image: {{ .Values.image.fullPath | default (printf "%s/%s:%s" .Values.repository .Values.image.name (.Values.image.tag | default .Chart.AppVersion)) }}
        {{- if .Values.edConfigContent }}
        command:
          - /edgedelta/edgedelta
        args:
          - -c
          - /var/edgedelta/config.yml
        {{- end }}
        ports:
          - name: compactor
            containerPort: {{ .Values.compactorProps.port }}
          {{- if .Values.storePort }}
          - name: metrics
            containerPort: {{ .Values.storePort }}
          {{- end }}
          {{- if .Values.profilerPort }}
          - name: profiler
            containerPort: {{ .Values.profilerPort }}
          {{- end }}
        env:
          - name: ED_FLEET_TYPE
            value: gateway
          - name: ED_AGENT_MODE
            value: compactor
          - name: ED_COMPACTOR_PORT
            value: "{{ .Values.compactorProps.port }}"
          - name: ED_HOST_OVERRIDE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: ED_K8S_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: ED_K8S_NAMESPACE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: ED_K8S_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          {{- if .Values.coordinatorProps.enabled }}
          - name: ED_COORDINATOR_CLIENT_ENABLED
            value: "1"
          {{- if .Values.coordinatorProps.endpoint }}
          - name: ED_COORDINATOR_CLIENT_ENDPOINT
            value: "{{ .Values.coordinatorProps.endpoint }}"
          {{- end }}
          {{- end }}
          {{- if .Values.apiKey }}
          - name: ED_API_KEY
            value: {{ .Values.apiKey | quote }}
          {{- else if .Values.secretApiKey.key }}
          {{ $lookupResult := lookup "v1" "Secret" .Release.Namespace (include "apiKeySecretName" .) }}
          {{- if or $lookupResult .Values.secretApiKey.value .Values.secretApiKey.enable }}
          - name: ED_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "apiKeySecretName" . }}
                key: {{ .Values.secretApiKey.key }}
          {{- end }}
          {{- end }}
          {{- if .Values.storePort }}
          - name: STORE_PORT
            value: "{{ .Values.storePort }}"
          {{- end }}
          {{- if .Values.profilerPort }}
          - name: PROFILER_PORT
            value: "{{ .Values.profilerPort }}"
          {{- end }}
          {{- if .Values.promPort }}
          - name: ED_PROM_PORT
            value: "{{ .Values.promPort }}"
          {{- end }}
          {{- if .Values.edTraceFiles }}
          - name: ED_TRACE_FILES
            value: {{ .Values.edTraceFiles | quote }}
          {{- end }}
          {{- if .Values.edApiEndpoint }}
          - name: ED_API_ENDPOINT
            value: {{ .Values.edApiEndpoint }}
          {{- end }}
          {{- if .Values.edBackendDisabled }}
          - name: ED_BACKEND_DISABLED
            value: "{{ .Values.edBackendDisabled }}"
          {{- end }}
          {{- if .Values.edSkipConfDownload }}
          - name: ED_SKIP_CONF_DOWNLOAD
            value: "{{ .Values.edSkipConfDownload }}"
          {{- end }}
          {{- if .Values.edTagOverride }}
          - name: ED_TAG_OVERRIDE
            value: {{ .Values.edTagOverride }}
          {{- end }}
          {{- if .Values.edClusterName }}
          - name: ED_CLUSTER_NAME
            value: {{ .Values.edClusterName }}
          {{- end }}
          {{- if .Values.edSkipTlsVerify }}
          - name: ED_SKIP_K8S_TLS_VERIFY
            value: "{{ .Values.edSkipTlsVerify }}"
          {{- end }}
          {{- if .Values.edOrgID }}
          - name: ED_ORG_ID
            value: {{ .Values.edOrgID }}
          {{- end }}
          {{- if .Values.httpProxy }}
          - name: HTTP_PROXY
            value: {{ .Values.httpProxy }}
          {{- end }}
          {{- if .Values.httpsProxy }}
          - name: HTTPS_PROXY
            value: {{ .Values.httpsProxy }}
          {{- end }}
          {{- if .Values.noProxy }}
          - name: NO_PROXY
            value: {{ .Values.noProxy }}
          {{- end }}
          {{- if .Values.edCustomTags }}
          - name:  ED_CUSTOM_TAGS
            value: "{{ .Values.edCustomTags }}"
          {{- end }}
          {{- if .Values.compactorProps.goMemLimit }}
          - name: GOMEMLIMIT
            value: {{ .Values.compactorProps.goMemLimit }}
          {{- end }}
          {{- if .Values.compactorProps.envs }}
          {{- range .Values.compactorProps.envs }}
          - name: {{ .name }}
            {{- if .value }}
            value: "{{ .value }}"
            {{- end }}
            {{- if .valueFrom }}
            valueFrom:
              {{ toYaml .valueFrom | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- else }}
          {{- range .Values.envs }}
          - name: {{ .name }}
            {{- if .value }}
            value: "{{ .value }}"
            {{- end }}
            {{- if .valueFrom }}
            valueFrom:
              {{ toYaml .valueFrom | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- range .Values.secrets }}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ .secretKeyRef.name }}
                key: {{ .secretKeyRef.key }}
          {{- end }}
        resources:
          {{- toYaml .Values.compactorProps.resources | nindent 12 }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          {{- if .Values.edConfigContent }}
          - name: config-volume
            mountPath: /var/edgedelta
          {{- end }}
      terminationGracePeriodSeconds: 60
      volumes:
      {{- if .Values.edConfigContent }}
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}
      {{- end }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "edgedelta.fullname" . }}-compactor-svc
  namespace: {{ .Release.Namespace }}
  labels:
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    edgedelta/agent-type: compactor
  ports:
    - port: {{ .Values.compactorProps.port }}
      name: compactor-port
{{- if .Values.compactorProps.autoscaling.enabled }}
---
apiVersion: {{ template "autoscaling.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "edgedelta.fullname" . }}-compactor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
  minReplicas: {{ .Values.compactorProps.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.compactorProps.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "edgedelta.fullname" . }}-compactor
  metrics:
    {{- if .Values.compactorProps.autoscaling.targetForMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.compactorProps.autoscaling.targetForMemoryUtilizationPercentage }}
    {{- end }}
    {{- if .Values.compactorProps.autoscaling.targetForCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.compactorProps.autoscaling.targetForCPUUtilizationPercentage }}
    {{- end }}
    {{- with .Values.compactorProps.autoscaling.customMetric -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.compactorProps.autoscaling.behavior }}
  behavior:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
