{{- if and .Values.serviceMonitor.enabled .Values.promPort }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "edgedelta.fullname" .}}-service-monitor
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- toYaml .Values.serviceMonitor.selector | nindent 4 }}
spec:
  {{- if .Values.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.serviceMonitor.jobLabel }}
  {{- end }}
  endpoints:
    - port: prom
      interval: 1m
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "edgedelta.selectorLabels" . | nindent 6 }}
      edgedelta/supports-prometheus: "true"
{{- end }}
{{- if or .Values.storePort .Values.promPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edgedelta.fullname" .}}-processor-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    edgedelta/supports-prometheus: "true"
spec:
  selector:
    {{- include "edgedelta.selectorLabels" . | nindent 4 }}
    edgedelta/agent-type: processor
  ports:
    {{- if .Values.storePort }}
    - name: metrics
      port: {{ .Values.storePort }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
    {{- if .Values.promPort }}
    - name: prom
      port: {{ .Values.promPort }}
      targetPort: prom
      protocol: TCP
    {{- end }}
{{- if .Values.rollUpProps.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edgedelta.fullname" .}}-rollup-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "edgedelta.selectorLabels" . | nindent 4 }}
    edgedelta/agent-type: rollup
  ports:
    {{- if .Values.storePort }}
    - name: metrics
      port: {{ .Values.storePort }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
    {{- if .Values.promPort }}
    - name: prom
      port: {{ .Values.promPort }}
      targetPort: prom
      protocol: TCP
    {{- end }}
{{- end }}
{{- end }}