{{- $pipelineId := .Values.secretApiKey.value | default .Values.apiKey }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "edgedelta.dnsSafeShortHash" $pipelineId }}-gw-svc
  namespace: {{ .Release.Namespace }}
  labels:
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  clusterIP: None
  selector:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    edgedelta/agent-type: processor
---
