kind: Service
apiVersion: v1
metadata:
  name: {{ include "edgedelta.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    edgedelta/agent-type: processor
  ports:
    - port: {{ .Values.gatewayProps.port }}
      name: gateway-port
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "edgedelta.fullname" . }}-headless-svc
  namespace: {{ .Release.Namespace }}
  labels:
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  clusterIP: None
  selector:
    {{- include "edgedelta.labels" . | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    edgedelta/agent-type: processor
---
